name: Build and Deploy Docker to ECR on Push

on:
  push:
    branches: [main]  # if push should go to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: clone the repository code to the runner
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: config for github actions to interact with AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: 
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      
      # Step 4: hash Dockerfile and files in context (for detecting changes)
      - name: Generate hash of Docker context
        run: |
         docker_context_hash=$(find . -type f -not -path './.git/*' -exec sha256sum {} \; | sha256sum | cut -d ' ' -f 1)
         echo "docker_context_hash=${docker_context_hash}" >> $GITHUB_ENV

      # Step 5:  hash of previously docker image
      - name: Get previous context hash from ECR
        run: |
          last_image_hash=$(aws ecr describe-images --repository-name ${{ secrets.ECR_REPOSITORY }} --query 'imageDetails[?imageTags[0]==`latest`].imageDigest' --output text)
          echo "last_image_hash=${last_image_hash}" >> $GITHUB_ENV

      # Step 6: Compare the hashes
      - name: determine if push is needed
        id: compare_digests
        run: |
          if [ "$docker_context_hash" != "$last_image_hash" ]; then
            echo "Docker context has changed. Pushing new image."
            echo "push_image=true" >> $GITHUB_ENV
          else
            echo "No changes in Docker context. Skipping push."
            echo "push_image=false" >> $GITHUB_ENV
          fi
          echo "::set-output name=push_image::$(echo $push_image)"

      # Step 7: Build and Push Docker Image if Needed
      - name: Build Docker image and push to ECR if changed
        if: steps.compare_digests.outputs.push_image == 'true'
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # Step 8: Register new ECS task definition revision
        # - retrieve current task definition from ECS using ECS CLI
        # - update task definition with new docker image URL
        # - create task definition JSON file with updated values
        # - register new task definition with ECS
        # - print new task definition revision number
        # - set new task definition revision number as env variable
      - name: Register new ECS task definition revision
        run: |
          task_definition=$(aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION_NAME }})
            
          new_task_definition=$(echo $task_definition | jq '.taskDefinition | .containerDefinitions[0].image = "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest"')
            
          echo $new_task_definition | jq '{ family: .family, containerDefinitions: .containerDefinitions }' > updated-task-definition.json
  
          new_task_definition_revision=$(aws ecs register-task-definition --cli-input-json file://updated-task-definition.json --query 'taskDefinition.revision' --output text)
          
          echo "New task definition revision: $new_task_definition_revision"
          echo "new_task_definition_revision=${new_task_definition_revision}" >> $GITHUB_ENV
      # Step 9: 
      - name: Update ECS service with new task definition
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER }} \
          --service ${{ secrets.ECS_SERVICE }} \
          --task-definition ${{ secrets.ECS_TASK_DEFINITION_NAME }}:$new_task_definition_revision