name: Build and Deploy Docker to ECR on Push

on:
  push:
    branches: [main]  # if push should go to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: clone the repository code to the runner
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: config for github actions to interact with AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: 
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      
      # Step 4: 
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
      
      # Step 5: Docker image must match the AWS ECR repository
      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
      
      # Step 6: 
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
  
      # Step 7: Register new ECS task definition revision
        # - retrieve the current task definition from ECS using the ECS CLI
        # - update task definition with the new docker image URL
        # - create new task definition JSON file with updated values
        # - register the new task definition with ECS
      - name: Register new ECS task definition revision
        run: |
          task_definition=$(aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION_NAME }})
            
          new_task_definition=$(echo $task_definition | jq '.taskDefinition | .containerDefinitions[0].image = "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest"')
            
          echo $new_task_definition | jq '{ family: .family, containerDefinitions: .containerDefinitions }' > updated-task-definition.json
  
          new_task_definition_revision=$(aws ecs register-task-definition --cli-input-json file://updated-task-definition.json --query 'taskDefinition.revision' --output text)
          
      # Step 8: 
      - name: Update ECS service with new task definition
        run: |
          aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
          --service ${{ secrets.ECS_SERVICE_NAME }} \
          --task-definition ${{ secrets.ECS_TASK_DEFINITION_NAME }}:$new_task_definition_revision